services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: party-manager-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PROFILE: "local"
      PORT: "8080"
      DB_URL: "jdbc:postgresql://db:5432/partymanager"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "root"

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "partymanager"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
