services:
  party-manager-api:
    container_name: party-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    image: party-manager-api:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prd"
      PORT: "8080"
      DB_URL: "jdbc:h2:mem:partymanager"
      DB_USERNAME: "sa"
      DB_PASSWORD: "pass"
